//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Managment_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSEntities : DbContext
    {
        public IMSEntities()
            : base("name=IMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CATEGORY> T_CATEGORY { get; set; }
        public virtual DbSet<T_INVOICE> T_INVOICE { get; set; }
        public virtual DbSet<T_ORDER> T_ORDER { get; set; }
        public virtual DbSet<T_PRODUCT> T_PRODUCT { get; set; }
        public virtual DbSet<T_PRODUCT_ORDER> T_PRODUCT_ORDER { get; set; }
        public virtual DbSet<T_USER> T_USER { get; set; }
        public virtual DbSet<V_PRODUCT> V_PRODUCT { get; set; }
        public virtual DbSet<V_TopSoldProducts> V_TopSoldProducts { get; set; }
        public virtual DbSet<V_LatestSoldProducts> V_LatestSoldProducts { get; set; }
        public virtual DbSet<V_INVOICE> V_INVOICE { get; set; }
    }
}
