//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INVOICE
    {
        public int I_ID { get; set; }
        public int I_O_ID { get; set; }
        public decimal I_TOTAL_AMOUNT { get; set; }
        public System.DateTime I_CREATED_AT { get; set; }
    
        public virtual T_ORDER T_ORDER { get; set; }
    }
}
