//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDER
    {
        public int O_ID { get; set; }
        public string O_COMPANY_NAME { get; set; }
        public string O_CREATER_NAME { get; set; }
        public decimal O_TOTAL_AMOUNT { get; set; }
        public System.DateTime O_CREATED_AT { get; set; }
        public bool O_STATUS { get; set; }
    }
}
