//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public int U_ID { get; set; }
        public string U_FULL_NAME { get; set; }
        public string U_USERNAME { get; set; }
        public string U_EMAIL { get; set; }
        public string U_COMPANY_NAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_ROLE { get; set; }
        public string U_IMAGE { get; set; }
    }
}
