//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Managment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCT
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Measure { get; set; }
        public string Category { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Image { get; set; }
    }
}
